// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPLQEMYKy2p1q9vKxKgfwM8pvAUl-H2Ps',
    appId: '1:485307769628:web:4ba245834722eecf7a90d9',
    messagingSenderId: '485307769628',
    projectId: 'uitm-student-tutor',
    authDomain: 'uitm-student-tutor.firebaseapp.com',
    storageBucket: 'uitm-student-tutor.firebasestorage.app',
    measurementId: 'G-MV1DR44C77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRe6QXSdwR0xKzDcWi9mS81Sc4ecuywc4',
    appId: '1:485307769628:android:975a7cc4b9d23ff87a90d9',
    messagingSenderId: '485307769628',
    projectId: 'uitm-student-tutor',
    storageBucket: 'uitm-student-tutor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeUfLuwlkUDtDG68_gylBdXuk7FKPHoMU',
    appId: '1:485307769628:ios:4587292f5bc772e87a90d9',
    messagingSenderId: '485307769628',
    projectId: 'uitm-student-tutor',
    storageBucket: 'uitm-student-tutor.firebasestorage.app',
    iosBundleId: 'com.example.uitmStudentTutor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeUfLuwlkUDtDG68_gylBdXuk7FKPHoMU',
    appId: '1:485307769628:ios:4587292f5bc772e87a90d9',
    messagingSenderId: '485307769628',
    projectId: 'uitm-student-tutor',
    storageBucket: 'uitm-student-tutor.firebasestorage.app',
    iosBundleId: 'com.example.uitmStudentTutor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPLQEMYKy2p1q9vKxKgfwM8pvAUl-H2Ps',
    appId: '1:485307769628:web:036095bfe9b8bdf77a90d9',
    messagingSenderId: '485307769628',
    projectId: 'uitm-student-tutor',
    authDomain: 'uitm-student-tutor.firebaseapp.com',
    storageBucket: 'uitm-student-tutor.firebasestorage.app',
    measurementId: 'G-286X4FDMDW',
  );
}
